# Generated by Django 4.0.4 on 2022-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp314', max_length=70),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
